// This file is automatically generated from your CSS. Any edits will be overwritten.
export const thoughtbox: string;
export const input: string;
export const header: string;
export const list: string;
