// This file is automatically generated from your CSS. Any edits will be overwritten.
export const project: string;
export const code: string;
export const docs: string;
export const addImage: string;
